# Generated by Django 2.0 on 2017-12-20 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0003_auto_20171220_1931'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='channel',
        ),
        migrations.RemoveField(
            model_name='channel',
            name='parent_channel',
        ),
        migrations.AddField(
            model_name='category',
            name='parent_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_categories', to='channels.Category'),
        ),
    ]
