# Generated by Django 2.0 on 2017-12-20 20:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0004_auto_20171220_2023'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='channel',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='channels.Channel'),
        ),
    ]
