# Generated by Django 2.0 on 2017-12-20 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0005_category_channel'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='channel',
            name='slug',
            field=models.SlugField(default=0),
            preserve_default=False,
        ),
    ]
