# Generated by Django 2.0 on 2017-12-20 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0006_auto_20171220_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='channel',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
