# Generated by Django 2.0 on 2017-12-27 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0007_auto_20171220_2151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='parent_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='channels.Category'),
        ),
        migrations.AlterField(
            model_name='channel',
            name='slug',
            field=models.SlugField(blank=True, help_text='The channel slug.', null=True),
        ),
    ]
